// flow-typed signature: 97c979d1793fc840aec47b5717491eb5
// flow-typed version: <<STUB>>/graphql-relay_vhttps://github.com/blackxored/graphql-relay-js#rn-base64/flow_v0.58.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-relay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-relay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-relay/lib/connection/arrayconnection' {
  declare module.exports: any;
}

declare module 'graphql-relay/lib/connection/connection' {
  declare module.exports: any;
}

declare module 'graphql-relay/lib/connection/connectiontypes' {
  declare module.exports: any;
}

declare module 'graphql-relay/lib/index' {
  declare module.exports: any;
}

declare module 'graphql-relay/lib/mutation/mutation' {
  declare module.exports: any;
}

declare module 'graphql-relay/lib/node/node' {
  declare module.exports: any;
}

declare module 'graphql-relay/lib/node/plural' {
  declare module.exports: any;
}

declare module 'graphql-relay/lib/utils/base64' {
  declare module.exports: any;
}

declare module 'graphql-relay/scripts/watch' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/__tests__/starWarsConnectionTests' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/__tests__/starWarsData' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/__tests__/starWarsMutationTests' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/__tests__/starWarsObjectIdentificationTests' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/__tests__/starWarsSchema' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/connection/__tests__/arrayconnection' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/connection/__tests__/connection' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/connection/arrayconnection' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/connection/connection' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/connection/connectiontypes' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/index' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/mutation/__tests__/mutation' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/mutation/mutation' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/node/__tests__/global' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/node/__tests__/node' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/node/__tests__/nodeasync' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/node/__tests__/plural' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/node/node' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/node/plural' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/utils/__tests__/base64' {
  declare module.exports: any;
}

declare module 'graphql-relay/src/utils/base64' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-relay/lib/connection/arrayconnection.js' {
  declare module.exports: $Exports<
    'graphql-relay/lib/connection/arrayconnection',
  >;
}
declare module 'graphql-relay/lib/connection/connection.js' {
  declare module.exports: $Exports<'graphql-relay/lib/connection/connection'>;
}
declare module 'graphql-relay/lib/connection/connectiontypes.js' {
  declare module.exports: $Exports<
    'graphql-relay/lib/connection/connectiontypes',
  >;
}
declare module 'graphql-relay/lib/index.js' {
  declare module.exports: $Exports<'graphql-relay/lib/index'>;
}
declare module 'graphql-relay/lib/mutation/mutation.js' {
  declare module.exports: $Exports<'graphql-relay/lib/mutation/mutation'>;
}
declare module 'graphql-relay/lib/node/node.js' {
  declare module.exports: $Exports<'graphql-relay/lib/node/node'>;
}
declare module 'graphql-relay/lib/node/plural.js' {
  declare module.exports: $Exports<'graphql-relay/lib/node/plural'>;
}
declare module 'graphql-relay/lib/utils/base64.js' {
  declare module.exports: $Exports<'graphql-relay/lib/utils/base64'>;
}
declare module 'graphql-relay/scripts/watch.js' {
  declare module.exports: $Exports<'graphql-relay/scripts/watch'>;
}
declare module 'graphql-relay/src/__tests__/starWarsConnectionTests.js' {
  declare module.exports: $Exports<
    'graphql-relay/src/__tests__/starWarsConnectionTests',
  >;
}
declare module 'graphql-relay/src/__tests__/starWarsData.js' {
  declare module.exports: $Exports<'graphql-relay/src/__tests__/starWarsData'>;
}
declare module 'graphql-relay/src/__tests__/starWarsMutationTests.js' {
  declare module.exports: $Exports<
    'graphql-relay/src/__tests__/starWarsMutationTests',
  >;
}
declare module 'graphql-relay/src/__tests__/starWarsObjectIdentificationTests.js' {
  declare module.exports: $Exports<
    'graphql-relay/src/__tests__/starWarsObjectIdentificationTests',
  >;
}
declare module 'graphql-relay/src/__tests__/starWarsSchema.js' {
  declare module.exports: $Exports<
    'graphql-relay/src/__tests__/starWarsSchema',
  >;
}
declare module 'graphql-relay/src/connection/__tests__/arrayconnection.js' {
  declare module.exports: $Exports<
    'graphql-relay/src/connection/__tests__/arrayconnection',
  >;
}
declare module 'graphql-relay/src/connection/__tests__/connection.js' {
  declare module.exports: $Exports<
    'graphql-relay/src/connection/__tests__/connection',
  >;
}
declare module 'graphql-relay/src/connection/arrayconnection.js' {
  declare module.exports: $Exports<
    'graphql-relay/src/connection/arrayconnection',
  >;
}
declare module 'graphql-relay/src/connection/connection.js' {
  declare module.exports: $Exports<'graphql-relay/src/connection/connection'>;
}
declare module 'graphql-relay/src/connection/connectiontypes.js' {
  declare module.exports: $Exports<
    'graphql-relay/src/connection/connectiontypes',
  >;
}
declare module 'graphql-relay/src/index.js' {
  declare module.exports: $Exports<'graphql-relay/src/index'>;
}
declare module 'graphql-relay/src/mutation/__tests__/mutation.js' {
  declare module.exports: $Exports<
    'graphql-relay/src/mutation/__tests__/mutation',
  >;
}
declare module 'graphql-relay/src/mutation/mutation.js' {
  declare module.exports: $Exports<'graphql-relay/src/mutation/mutation'>;
}
declare module 'graphql-relay/src/node/__tests__/global.js' {
  declare module.exports: $Exports<'graphql-relay/src/node/__tests__/global'>;
}
declare module 'graphql-relay/src/node/__tests__/node.js' {
  declare module.exports: $Exports<'graphql-relay/src/node/__tests__/node'>;
}
declare module 'graphql-relay/src/node/__tests__/nodeasync.js' {
  declare module.exports: $Exports<
    'graphql-relay/src/node/__tests__/nodeasync',
  >;
}
declare module 'graphql-relay/src/node/__tests__/plural.js' {
  declare module.exports: $Exports<'graphql-relay/src/node/__tests__/plural'>;
}
declare module 'graphql-relay/src/node/node.js' {
  declare module.exports: $Exports<'graphql-relay/src/node/node'>;
}
declare module 'graphql-relay/src/node/plural.js' {
  declare module.exports: $Exports<'graphql-relay/src/node/plural'>;
}
declare module 'graphql-relay/src/utils/__tests__/base64.js' {
  declare module.exports: $Exports<'graphql-relay/src/utils/__tests__/base64'>;
}
declare module 'graphql-relay/src/utils/base64.js' {
  declare module.exports: $Exports<'graphql-relay/src/utils/base64'>;
}
